---
- name: Install/Reinstall check_mk packages
  apt:
    name: "{{ check_mk_packages }}"
    state: latest
    update_cache: yes

- name: Add nagios local_scripts from template
  template:
    src: "{{ item }}.j2"
    dest: "/usr/lib/check_mk_agent/local/{{ item }}"
    force: yes
    mode: 0644
  with_items: "{{ check_mk_local_scripts_by_template }}"
  when: check_mk_local_scripts_by_template|length > 0

- name: Add nagios local_scripts from file
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/check_mk_agent/local/{{ item }}"
    force: yes
    mode: 0644
  with_items: "{{ check_mk_local_scripts_file }}"
  when: check_mk_local_scripts_file|length > 0

- name: Add nagios plugins from template
  template:
    src: "{{ item }}.j2"
    dest: "/usr/lib/check_mk_agent/plugins/{{ item }}"
    force: yes
    mode: 0644
  with_items: "{{ check_mk_plugins_by_template }}"
  when: check_mk_plugins_by_template|length > 0

- name: Add nagios plugins from file
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/check_mk_agent/plugins/{{ item }}"
    force: yes
    mode: 0644
  with_items: "{{ check_mk_plugins_file }}"
  when: check_mk_plugins_file|length > 0