---

- hosts: all
  remote_user: root
  vars_files:
    - vars/apache2.yml
    - vars/metacentrum_monitoring.yml
    - vars/shibboleth.yml
    - vars/unattended_upgrades.yml
    - vars/yubikey.yml
  roles:
    - {role: pajavyskocil.apache2, tag: install }
#    - {role: pajavyskocil.unattended_upgrades, tag: install }
#    - {role: pajavyskocil.metacentrum_monitoring, tag: install }
#    - {role: pajavyskocil.yubikeys, tag: install }
#    - {role: pajavyskocil.shibboleth, tag: install }

