---

- hosts: all
  remote_user: root
  vars:
    action: "start"
  vars_files:
    - vars/apache2.yml
    - vars/unattended_upgrades.yml
    - vars/metacentrum_monitoring.yml
    - vars/shibboleth.yml
    - vars/yubikey.yml
    - vars/elastic.yml
  roles:
#    - {role: pajavyskocil.apache2}
#    - {role: pajavyskocil.unattended_upgrades}
#    - {role: pajavyskocil.metacentrum_monitoring}
#    - {role: pajavyskocil.yubikeys}
    - {role: pajavyskocil.shibboleth}
#    - {role: pajavyskocil.elk_stack}


