---
# Install java
- include_tasks: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Add Elastic apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elastic repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main'
    state: present

- name: Logstash | Install | Check if Logstash is already installed.
  stat: path=/etc/init.d/logstash
  register: logstash_installed

- name: Logstash | Install | Update apt cache if repository just added.
  apt: update_cache=yes
  when: not logstash_installed.stat.exists

- name: Logstash | Install | Install Logstash.
  apt:
    name: logstash
    state: present

- name: Logstash | Install | Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  notify: restart logstash


- name: Elasticsearch | Install | Check if Elasticsearch is already installed.
  stat: path=/etc/init.d/elasticsearch
  register: elasticsearch_installed

- name: Elasticsearch | Install | Update apt cache if repository just added.
  apt: update_cache=yes
  when: not elasticsearch_installed.stat.exists

- name: Elasticsearch | Install | Install Elasticsearch.
  apt:
    name: elasticsearch
    state: present

- name: Elasticsearch | Install | Add Elasticsearch user to adm group (Debian).
  user:
    name: elasticsearch
    group: elasticsearch
    groups: adm
  notify: restart elasticsearch

- name: Kibana | Install | Check if Kibana is already installed.
  stat: path=/etc/init.d/kibana
  register: kibana_installed

- name: Kibana | Install | Update apt cache if repository just added.
  apt: update_cache=yes
  when: action == "install" and not kibana_installed.stat.exists

- name: Kibana | Install | Install Kibana.
  apt:
    name: kibana
    state: present

- name: Kibana | Install | Add Kibana user to adm group (Debian).
  user:
    name: kibana
    group: kibana
    groups: adm
  notify: restart kibana