---
- name: Copy shibboleth2.xml
  template:
    src: "shibboleth2.xml.j2"
    dest: "/etc/shibboleth/shibboleth2.xml"
    force: yes
    mode: 0644

- name: Copy attribute-map.xml
  template:
    src: "attribute-map.xml.j2"
    dest: "/etc/shibboleth/attribute-map.xml"
    force: yes
    mode: 0644

- name: Get info if attribute-policy.xml template is exist
  local_action: stat path=templates/attribute-policy.xml.j2
  register: st

- name: Copy attribute-policy.xml
  template:
    src: "attribute-policy.xml.j2"
    dest: "/etc/shibboleth/attribute-policy.xml"
    force: yes
    mode: 0644
  when: st.stat.exists