---
# specific tasks
- include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Copy shibboleth2.xml
  template:
    src: "shibboleth2.xml.j2"
    dest: "/etc/shibboleth/shibboleth2.xml"
    force: yes
    mode: 0644

- name: Copy attribute-map.xml
  template:
    src: "attribute-map.xml.j2"
    dest: "/etc/shibboleth/attribute-map.xml"
    force: yes
    mode: 0644

- name: Get info if attribute-policy.xml template is exist
  local_action: stat path=templates/attribute-policy.xml.j2
  register: st

- name: Copy attribute-policy.xml
  template:
    src: "attribute-policy.xml.j2"
    dest: "/etc/shibboleth/attribute-policy.xml"
    force: yes
    mode: 0644
  when: st.stat.exists

- name: Generate Shibboleth key and cert
  command: shib-keygen -h {{ hostname }} -e {{ shib_sp_entity_id }}
  args:
    chdir: /etc/shibboleth
    creates: /etc/shibboleth/sp-key.pem
  notify:
    - "restart shibd"

- name: Restart server if needed
  meta: flush_handlers